/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_v1_health__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Investigations */
        get: operations["list_investigations_api_v1_investigations__get"];
        put?: never;
        /** Create Investigation */
        post: operations["create_investigation_api_v1_investigations__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Investigation */
        get: operations["get_investigation_api_v1_investigations__investigation_id__get"];
        put?: never;
        post?: never;
        /** Delete Investigation */
        delete: operations["delete_investigation_api_v1_investigations__investigation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_investigations__investigation_id__documents_get"];
        put?: never;
        /** Upload Documents */
        post: operations["upload_documents_api_v1_investigations__investigation_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}/documents/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture Web Page */
        post: operations["capture_web_page_api_v1_investigations__investigation_id__documents_capture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_investigations__investigation_id__documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_api_v1_investigations__investigation_id__documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}/documents/{document_id}/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Text */
        get: operations["get_document_text_api_v1_investigations__investigation_id__documents__document_id__text_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}/documents/{document_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Document */
        post: operations["retry_document_api_v1_investigations__investigation_id__documents__document_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}/chunks/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chunk With Context */
        get: operations["get_chunk_with_context_api_v1_investigations__investigation_id__chunks__chunk_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description Stream SSE events for an investigation's document processing.
         */
        get: operations["stream_events_api_v1_investigations__investigation_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}/entities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Entities
         * @description Return paginated entity list with confidence scores and summary counts.
         */
        get: operations["list_entities_api_v1_investigations__investigation_id__entities__get"];
        put?: never;
        /**
         * Create Entity
         * @description Create a manual entity in the investigation's knowledge graph.
         */
        post: operations["create_entity_api_v1_investigations__investigation_id__entities__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Entity Detail
         * @description Return entity detail with relationships and provenance sources.
         */
        get: operations["get_entity_detail_api_v1_investigations__investigation_id__entities__entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Entity
         * @description Update an entity's name and/or source annotation.
         */
        patch: operations["update_entity_api_v1_investigations__investigation_id__entities__entity_id__patch"];
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}/relationships/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Relationship
         * @description Create a manual relationship between two entities in the investigation's knowledge graph.
         */
        post: operations["create_relationship_api_v1_investigations__investigation_id__relationships__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}/cross-links/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cross Investigation Links
         * @description Find entities in this investigation that also appear in other investigations.
         */
        get: operations["get_cross_investigation_links_api_v1_investigations__investigation_id__cross_links__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}/graph/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subgraph */
        get: operations["get_subgraph_api_v1_investigations__investigation_id__graph__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}/graph/neighbors/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Neighbors */
        get: operations["get_neighbors_api_v1_investigations__investigation_id__graph_neighbors__entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}/query/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query Investigation
         * @description Execute a natural language query against an investigation's knowledge graph.
         *
         *     Returns an SSE stream with query pipeline events.
         */
        post: operations["query_investigation_api_v1_investigations__investigation_id__query__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream System Events
         * @description Stream SSE events for system-level service status changes.
         */
        get: operations["stream_system_events_api_v1_events_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_documents_api_v1_investigations__investigation_id__documents_post */
        Body_upload_documents_api_v1_investigations__investigation_id__documents_post: {
            /** Files */
            files: string[];
        };
        /** CaptureWebPageRequest */
        CaptureWebPageRequest: {
            /** Url */
            url: string;
        };
        /** ChunkWithContextResponse */
        ChunkWithContextResponse: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Document Filename */
            document_filename: string;
            /** Sequence Number */
            sequence_number: number;
            /** Total Chunks */
            total_chunks: number;
            /** Text */
            text: string;
            /** Page Start */
            page_start: number;
            /** Page End */
            page_end: number;
            /** Context Before */
            context_before: string | null;
            /** Context After */
            context_after: string | null;
        };
        /** ConversationTurn */
        ConversationTurn: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** CrossInvestigationMatch */
        CrossInvestigationMatch: {
            /** Entity Name */
            entity_name: string;
            /** Entity Type */
            entity_type: string;
            /** Match Confidence */
            match_confidence: number;
            /** Match Type */
            match_type: string;
            /** Source Entity Id */
            source_entity_id: string;
            /** Source Relationship Count */
            source_relationship_count: number;
            /** Source Confidence Score */
            source_confidence_score: number;
            /** Investigations */
            investigations: components["schemas"]["InvestigationEntityInfo"][];
        };
        /** CrossInvestigationResponse */
        CrossInvestigationResponse: {
            /** Matches */
            matches: components["schemas"]["CrossInvestigationMatch"][];
            /** Total Matches */
            total_matches: number;
            /** Query Duration Ms */
            query_duration_ms: number;
        };
        /** DocumentListResponse */
        DocumentListResponse: {
            /** Items */
            items: components["schemas"]["DocumentResponse"][];
            /** Total */
            total: number;
        };
        /** DocumentResponse */
        DocumentResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Investigation Id
             * Format: uuid
             */
            investigation_id: string;
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 Checksum */
            sha256_checksum: string;
            /**
             * Document Type
             * @default pdf
             */
            document_type: string;
            /** Source Url */
            source_url?: string | null;
            /** Status */
            status: string;
            /** Page Count */
            page_count: number | null;
            /** Entity Count */
            entity_count?: number | null;
            /** Extraction Confidence */
            extraction_confidence?: number | null;
            /** Extracted Text */
            extracted_text?: string | null;
            /** Ocr Method */
            ocr_method?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Failed Stage */
            failed_stage?: string | null;
            /**
             * Retry Count
             * @default 0
             */
            retry_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Extraction Quality */
            readonly extraction_quality: string | null;
        };
        /** DocumentTextResponse */
        DocumentTextResponse: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Filename */
            filename: string;
            /** Page Count */
            page_count: number | null;
            /** Extracted Text */
            extracted_text: string | null;
            /** Status */
            status: string;
        };
        /** EntityCreateRequest */
        EntityCreateRequest: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Source Annotation */
            source_annotation?: string | null;
        };
        /** EntityDetailResponse */
        EntityDetailResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Confidence Score */
            confidence_score: number;
            /** Investigation Id */
            investigation_id: string;
            /** Relationships */
            relationships: components["schemas"]["EntityRelationship"][];
            /** Sources */
            sources: components["schemas"]["EntitySource"][];
            /** Evidence Strength */
            evidence_strength: string;
            /**
             * Source
             * @default extracted
             */
            source: string;
            /** Source Annotation */
            source_annotation?: string | null;
            /**
             * Aliases
             * @default []
             */
            aliases: string[];
        };
        /** EntityListItem */
        EntityListItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Confidence Score */
            confidence_score: number;
            /** Source Count */
            source_count: number;
            /** Evidence Strength */
            evidence_strength: string;
            /**
             * Source
             * @default extracted
             */
            source: string;
        };
        /** EntityListResponse */
        EntityListResponse: {
            /** Items */
            items: components["schemas"]["EntityListItem"][];
            /** Total */
            total: number;
            summary: components["schemas"]["EntityTypeSummary"];
        };
        /** EntityRelationship */
        EntityRelationship: {
            /** Relation Type */
            relation_type: string;
            /** Target Id */
            target_id: string | null;
            /** Target Name */
            target_name: string | null;
            /** Target Type */
            target_type: string | null;
            /** Confidence Score */
            confidence_score: number;
        };
        /** EntitySource */
        EntitySource: {
            /** Document Id */
            document_id: string;
            /** Document Filename */
            document_filename: string;
            /** Chunk Id */
            chunk_id: string;
            /** Page Start */
            page_start: number;
            /** Page End */
            page_end: number;
            /** Text Excerpt */
            text_excerpt: string;
        };
        /** EntityTypeSummary */
        EntityTypeSummary: {
            /** People */
            people: number;
            /** Organizations */
            organizations: number;
            /** Locations */
            locations: number;
            /** Total */
            total: number;
        };
        /** EntityUpdateRequest */
        EntityUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Source Annotation */
            source_annotation?: string | null;
        };
        /** GraphEdge */
        GraphEdge: {
            /**
             * Group
             * @constant
             */
            group: "edges";
            data: components["schemas"]["GraphEdgeData"];
        };
        /** GraphEdgeData */
        GraphEdgeData: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Type */
            type: string;
            /** Confidence Score */
            confidence_score: number;
            /**
             * Origin
             * @default extracted
             */
            origin?: string;
            /** Source Annotation */
            source_annotation?: string | null;
        };
        /** GraphNode */
        GraphNode: {
            /**
             * Group
             * @constant
             */
            group: "nodes";
            data: components["schemas"]["GraphNodeData"];
        };
        /** GraphNodeData */
        GraphNodeData: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Confidence Score */
            confidence_score: number;
            /** Relationship Count */
            relationship_count: number;
        };
        /** GraphResponse */
        GraphResponse: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            /** Total Nodes */
            total_nodes: number;
            /** Total Edges */
            total_edges: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            status: components["schemas"]["OverallStatusEnum"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Services */
            services: {
                [key: string]: components["schemas"]["ServiceStatus"] | components["schemas"]["OllamaStatus"];
            };
            /** Warnings */
            warnings: string[];
        };
        /** InvestigationCreate */
        InvestigationCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** InvestigationEntityInfo */
        InvestigationEntityInfo: {
            /** Investigation Id */
            investigation_id: string;
            /** Investigation Name */
            investigation_name: string;
            /** Entity Id */
            entity_id: string;
            /** Relationship Count */
            relationship_count: number;
            /** Confidence Score */
            confidence_score: number;
        };
        /** InvestigationListResponse */
        InvestigationListResponse: {
            /** Items */
            items: components["schemas"]["InvestigationResponse"][];
            /** Total */
            total: number;
        };
        /** InvestigationResponse */
        InvestigationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Document Count
             * @default 0
             */
            document_count: number;
            /**
             * Entity Count
             * @default 0
             */
            entity_count: number;
        };
        /** ModelInfo */
        ModelInfo: {
            /** Name */
            name: string;
            /** Available */
            available: boolean;
        };
        /** OllamaStatus */
        OllamaStatus: {
            status: components["schemas"]["StatusEnum"];
            /** Detail */
            detail: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /** Models Ready */
            models_ready: boolean;
            /** Models */
            models: components["schemas"]["ModelInfo"][];
        };
        /**
         * OverallStatusEnum
         * @enum {string}
         */
        OverallStatusEnum: "healthy" | "degraded" | "unhealthy";
        /** RelationshipCreateRequest */
        RelationshipCreateRequest: {
            /** Source Entity Id */
            source_entity_id: string;
            /** Target Entity Id */
            target_entity_id: string;
            /** Type */
            type: string;
            /** Source Annotation */
            source_annotation?: string | null;
        };
        /** RelationshipResponse */
        RelationshipResponse: {
            /** Id */
            id: string;
            /** Source Entity Id */
            source_entity_id: string;
            /** Target Entity Id */
            target_entity_id: string;
            /** Source Entity Name */
            source_entity_name: string;
            /** Target Entity Name */
            target_entity_name: string;
            /** Type */
            type: string;
            /** Confidence Score */
            confidence_score: number;
            /** Source */
            source: string;
            /** Source Annotation */
            source_annotation?: string | null;
            /**
             * Already Existed
             * @default false
             */
            already_existed?: boolean;
        };
        /** QueryRequest */
        QueryRequest: {
            /** Question */
            question: string;
            /** Conversation History */
            conversation_history?: components["schemas"]["ConversationTurn"][] | null;
        };
        /** ServiceStatus */
        ServiceStatus: {
            status: components["schemas"]["StatusEnum"];
            /** Detail */
            detail: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * StatusEnum
         * @enum {string}
         */
        StatusEnum: "healthy" | "unhealthy" | "unavailable";
        /** UploadDocumentsResponse */
        UploadDocumentsResponse: {
            /** Items */
            items: components["schemas"]["DocumentResponse"][];
            /** Errors */
            errors: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_investigations_api_v1_investigations__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_investigation_api_v1_investigations__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_investigation_api_v1_investigations__investigation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_investigation_api_v1_investigations__investigation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_investigations__investigation_id__documents_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_documents_api_v1_investigations__investigation_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_documents_api_v1_investigations__investigation_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadDocumentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capture_web_page_api_v1_investigations__investigation_id__documents_capture_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureWebPageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_investigations__investigation_id__documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_v1_investigations__investigation_id__documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_text_api_v1_investigations__investigation_id__documents__document_id__text_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentTextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_document_api_v1_investigations__investigation_id__documents__document_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chunk_with_context_api_v1_investigations__investigation_id__chunks__chunk_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
                chunk_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkWithContextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_v1_investigations__investigation_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entities_api_v1_investigations__investigation_id__entities__get: {
        parameters: {
            query?: {
                type?: string | null;
                search?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_entity_api_v1_investigations__investigation_id__entities__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entity_detail_api_v1_investigations__investigation_id__entities__entity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_entity_api_v1_investigations__investigation_id__entities__entity_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_relationship_api_v1_investigations__investigation_id__relationships__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationshipCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cross_investigation_links_api_v1_investigations__investigation_id__cross_links__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrossInvestigationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subgraph_api_v1_investigations__investigation_id__graph__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                entity_types?: string | null;
                document_id?: string | null;
            };
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_neighbors_api_v1_investigations__investigation_id__graph_neighbors__entity_id__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                investigation_id: string;
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_investigation_api_v1_investigations__investigation_id__query__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_system_events_api_v1_events_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
